apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: urbanhub-postgres
    url: postgres:5432
    user: urbanhub
    secureJsonData:
      password: urbanhub
    jsonData:
      database: urbanhub
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true